version: "3.3"

services:
  ripper:
    container_name: simple-python-http-server-with-upload
    image: python:3.9.1-alpine
    restart: always
    working_dir: "/app"
    command: "python3 server.py"
    ports:
      - "10140:8000"
    expose:
      - "8000"
    volumes:
      - "./app/:/app/:rw"
